import { useState, type FormEvent } from 'react';
import { ProductionStore } from '../context/useProductionStore';
import { AlertOctagon, KeyRound, ShieldAlert, CheckCircle2, X } from 'lucide-react';
import { getMonthName, getISTCurrentMonth } from '../utils/formatters';

interface ZeroSystemModalProps {
  store: ProductionStore;
}

export function ZeroSystemModal({ store }: ZeroSystemModalProps) {
  const { db, requestZeroOtp, verifyZeroOtp, executeZero, selectedMonth } = store;

  const currentMonthStr = getISTCurrentMonth();
  const [scope, setScope] = useState<'current_month' | 'selected_worker' | 'selected_piece_size'>('current_month');
  const [targetWorkerId, setTargetWorkerId] = useState<string>(db.workers[0]?.id || '');
  const [targetPieceSizeId, setTargetPieceSizeId] = useState<string>(db.pieceSizes[0]?.id || '');

  // Wizard steps: 1 = Scope Selection, 2 = Enter OTP, 3 = Type RESET, 4 = Completed
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [otpValue, setOtpValue] = useState('');
  const [otpPreview, setOtpPreview] = useState<string | null>(null);
  const [confirmText, setConfirmText] = useState('');
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [resetCount, setResetCount] = useState<number>(0);

  const monthStatusObj = db.monthStatuses.find((m) => m.month === currentMonthStr);
  const isMonthLocked = monthStatusObj?.status === 'LOCKED' || monthStatusObj?.isClosed;

  const handleRequestOtp = async () => {
    if (isMonthLocked) {
      setFeedback({ type: 'error', message: 'Current month is locked. Zero System cannot reset locked months.' });
      return;
    }

    setLoading(true);
    setFeedback(null);

    const targetId = scope === 'selected_worker' ? targetWorkerId : scope === 'selected_piece_size' ? targetPieceSizeId : undefined;
    const res = await requestZeroOtp(scope, targetId, currentMonthStr);
    setLoading(false);

    if (res.success) {
      setOtpPreview(res.otpPreview || null);
      setStep(2);
      setFeedback({ type: 'success', message: 'Security OTP generated by server. Enter code below to verify.' });
    } else {
      setFeedback({ type: 'error', message: res.message || 'Failed to request OTP.' });
    }
  };

  const handleVerifyOtp = async (e: FormEvent) => {
    e.preventDefault();
    if (!otpValue || otpValue.trim().length !== 6) {
      setFeedback({ type: 'error', message: 'Please enter the 6-digit OTP.' });
      return;
    }
    setLoading(true);
    setFeedback(null);
    const res = await verifyZeroOtp(otpValue.trim());
    setLoading(false);

    if (res.success) {
      setFeedback(null);
      setStep(3);
    } else {
      setFeedback({ type: 'error', message: res.message || 'Server rejected OTP verification.' });
    }
  };

  const handleFinalExecute = async (e: FormEvent) => {
    e.preventDefault();
    if (confirmText.trim().toUpperCase() !== 'RESET') {
      setFeedback({ type: 'error', message: "You must type exactly 'RESET' to confirm." });
      return;
    }

    setLoading(true);
    setFeedback(null);

    const targetId = scope === 'selected_worker' ? targetWorkerId : scope === 'selected_piece_size' ? targetPieceSizeId : undefined;
    const res = await executeZero(otpValue.trim(), scope, targetId, currentMonthStr);
    setLoading(false);

    if (res.success) {
      setStep(4);
      setFeedback({ type: 'success', message: res.message || 'Zero operation completed.' });
    } else {
      setFeedback({ type: 'error', message: res.message || 'Verification failed. Action aborted.' });
    }
  };

  const handleResetWizard = () => {
    setStep(1);
    setOtpValue('');
    setOtpPreview(null);
    setConfirmText('');
    setFeedback(null);
  };

  return (
    <div className="space-y-4 sm:space-y-5">
      {/* Header Banner */}
      <div className="bg-red-50 border border-red-200 rounded-xl p-4 shadow-sm space-y-1.5">
        <div className="flex items-center space-x-3 text-red-600">
          <AlertOctagon className="w-6 h-6 flex-shrink-0" />
          <div>
            <h2 className="text-sm sm:text-base font-bold uppercase tracking-tight text-red-950">ZERO SYSTEM (FACTORY RESET)</h2>
            <p className="text-xs text-red-700 font-medium">
              High-security destructive operation guarded by two-factor authorization and audit logs
            </p>
          </div>
        </div>
      </div>

      {feedback && (
        <div
          className={`p-3 rounded-lg text-xs font-bold flex items-center space-x-2 ${
            feedback.type === 'success'
              ? 'bg-green-50 border border-green-200 text-green-800'
              : 'bg-red-50 border border-red-200 text-red-800'
          }`}
        >
          {feedback.type === 'success' ? <CheckCircle2 className="w-4 h-4" /> : <ShieldAlert className="w-4 h-4" />}
          <span>{feedback.message}</span>
        </div>
      )}

      {/* Main Container */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm max-w-xl space-y-4">
        {/* Step Indicator */}
        <div className="flex items-center justify-between border-b border-slate-100 pb-3 text-[11px] font-bold uppercase tracking-wider">
          <span className={step === 1 ? 'text-red-600' : 'text-slate-400'}>1. Scope</span>
          <span className="text-slate-300">→</span>
          <span className={step === 2 ? 'text-red-600' : 'text-slate-400'}>2. Security OTP</span>
          <span className="text-slate-300">→</span>
          <span className={step === 3 ? 'text-red-600' : 'text-slate-400'}>3. Confirm</span>
          <span className="text-slate-300">→</span>
          <span className={step === 4 ? 'text-green-600' : 'text-slate-400'}>4. Execution</span>
        </div>

        {/* STEP 1: Select Scope */}
        {step === 1 && (
          <div className="space-y-3.5">
            <div className="p-3 rounded-lg bg-slate-50 border border-slate-200 text-xs text-slate-600 space-y-1">
              <div className="font-bold text-slate-900 uppercase">Protected Target Month:</div>
              <div className="text-blue-700 font-mono font-bold text-sm">{getMonthName(currentMonthStr)}</div>
              <p className="text-[11px] text-slate-500 pt-0.5">
                Zero System can only operate on the current open month. Locked historical months cannot be modified.
              </p>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-600 uppercase mb-1.5">Select Reset Scope</label>
              <div className="space-y-2">
                <label className="flex items-center space-x-3 p-3 rounded-lg bg-slate-50 border border-slate-200 cursor-pointer hover:bg-slate-100 transition-colors">
                  <input
                    type="radio"
                    name="scope"
                    checked={scope === 'current_month'}
                    onChange={() => setScope('current_month')}
                    className="accent-red-600 w-4 h-4 cursor-pointer"
                  />
                  <div>
                    <div className="text-xs font-bold text-slate-900">Reset Entire Current Month</div>
                    <div className="text-[11px] text-slate-500">Zero all records across all workers for {currentMonthStr}</div>
                  </div>
                </label>

                <label className="flex items-center space-x-3 p-3 rounded-lg bg-slate-50 border border-slate-200 cursor-pointer hover:bg-slate-100 transition-colors">
                  <input
                    type="radio"
                    name="scope"
                    checked={scope === 'selected_worker'}
                    onChange={() => setScope('selected_worker')}
                    className="accent-red-600 w-4 h-4 cursor-pointer"
                  />
                  <div>
                    <div className="text-xs font-bold text-slate-900">Reset Selected Worker</div>
                    <div className="text-[11px] text-slate-500">Zero entries only for one specific worker in {currentMonthStr}</div>
                  </div>
                </label>

                <label className="flex items-center space-x-3 p-3 rounded-lg bg-slate-50 border border-slate-200 cursor-pointer hover:bg-slate-100 transition-colors">
                  <input
                    type="radio"
                    name="scope"
                    checked={scope === 'selected_piece_size'}
                    onChange={() => setScope('selected_piece_size')}
                    className="accent-red-600 w-4 h-4 cursor-pointer"
                  />
                  <div>
                    <div className="text-xs font-bold text-slate-900">Reset Selected Piece Size</div>
                    <div className="text-[11px] text-slate-500">Zero entries only for one bottle format in {currentMonthStr}</div>
                  </div>
                </label>
              </div>
            </div>

            {scope === 'selected_worker' && (
              <div>
                <label className="block text-xs font-bold text-slate-600 uppercase mb-1">Choose Worker to Zero</label>
                <select
                  value={targetWorkerId}
                  onChange={(e) => setTargetWorkerId(e.target.value)}
                  className="w-full py-2 px-3 rounded-lg bg-slate-50 border border-slate-300 text-slate-900 font-medium text-xs"
                >
                  {db.workers.map((w) => (
                    <option key={w.id} value={w.id}>
                      {w.firstName} ({w.fullName})
                    </option>
                  ))}
                </select>
              </div>
            )}

            {scope === 'selected_piece_size' && (
              <div>
                <label className="block text-xs font-bold text-slate-600 uppercase mb-1">Choose Piece Size to Zero</label>
                <select
                  value={targetPieceSizeId}
                  onChange={(e) => setTargetPieceSizeId(e.target.value)}
                  className="w-full py-2 px-3 rounded-lg bg-slate-50 border border-slate-300 text-slate-900 font-medium text-xs"
                >
                  {db.pieceSizes.map((ps) => (
                    <option key={ps.id} value={ps.id}>
                      {ps.displayName}
                    </option>
                  ))}
                </select>
              </div>
            )}

            <button
              type="button"
              disabled={loading || isMonthLocked}
              onClick={handleRequestOtp}
              className="w-full py-2.5 px-4 rounded-lg bg-red-600 hover:bg-red-700 active:scale-98 text-white font-bold text-xs uppercase tracking-wider shadow-xs flex items-center justify-center space-x-1.5 cursor-pointer disabled:opacity-50"
            >
              <KeyRound className="w-3.5 h-3.5" />
              <span>{loading ? 'Requesting...' : 'REQUEST ZERO OTP'}</span>
            </button>
          </div>
        )}

        {/* STEP 2: Enter OTP */}
        {step === 2 && (
          <form onSubmit={handleVerifyOtp} className="space-y-3.5">
            <div className="p-3 rounded-lg bg-blue-50 border border-blue-200 text-xs text-blue-900 space-y-1.5">
              <div className="font-bold uppercase text-slate-900 flex items-center space-x-1.5">
                <KeyRound className="w-3.5 h-3.5 text-blue-600" />
                <span>Security OTP Generated:</span>
              </div>
              <div className="font-mono text-2xl tracking-[0.3em] font-extrabold text-blue-700 text-center py-2 bg-white rounded-lg border border-blue-200">
                {otpPreview}
              </div>
              <p className="text-[11px] text-slate-500 text-center">
                Valid for 5 minutes. Enter the code below to verify authority.
              </p>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-600 uppercase mb-1">Enter 6-Digit OTP</label>
              <input
                type="text"
                maxLength={6}
                inputMode="numeric"
                autoFocus
                value={otpValue}
                onChange={(e) => setOtpValue(e.target.value)}
                placeholder="123456"
                className="w-full py-2.5 px-4 text-center tracking-[0.5em] font-mono font-bold text-xl rounded-lg bg-slate-50 border border-slate-300 text-slate-900 focus:ring-2 focus:ring-red-500 focus:outline-none"
              />
            </div>

            <div className="flex items-center space-x-2 pt-1">
              <button
                type="button"
                onClick={handleResetWizard}
                className="w-1/2 py-2 rounded-lg bg-white hover:bg-slate-50 text-slate-700 text-xs font-bold border border-slate-300 shadow-xs cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={otpValue.length !== 6}
                className="w-1/2 py-2 rounded-lg bg-red-600 hover:bg-red-700 text-white text-xs font-bold shadow-xs uppercase tracking-wider cursor-pointer disabled:opacity-50"
              >
                Verify OTP
              </button>
            </div>
          </form>
        )}

        {/* STEP 3: Final Type RESET Confirmation */}
        {step === 3 && (
          <form onSubmit={handleFinalExecute} className="space-y-3.5">
            <div className="p-3 rounded-lg bg-red-50 border border-red-200 text-red-900 text-xs space-y-2">
              <div className="font-bold text-red-950 text-xs uppercase flex items-center justify-between">
                <span>Final Safety Verification</span>
                <span className="bg-red-200 text-red-900 text-[10px] px-2 py-0.5 rounded font-mono font-bold">OTP VERIFIED</span>
              </div>
              
              <div className="bg-white rounded p-2.5 border border-red-200 space-y-1 text-slate-700 text-xs">
                <div className="flex justify-between">
                  <span className="font-medium text-slate-500">Operation Scope:</span>
                  <span className="font-bold text-slate-900 uppercase">
                    {scope === 'current_month' && 'Entire Current Month'}
                    {scope === 'selected_worker' && 'Specific Worker Production'}
                    {scope === 'selected_piece_size' && 'Specific Piece Size Production'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="font-medium text-slate-500">Target Month:</span>
                  <span className="font-mono font-bold text-slate-900">{currentMonthStr}</span>
                </div>
                {scope === 'selected_worker' && (
                  <div className="flex justify-between">
                    <span className="font-medium text-slate-500">Target Worker:</span>
                    <span className="font-bold text-slate-900">
                      {db.workers.find((w) => w.id === targetWorkerId)?.fullName || targetWorkerId}
                    </span>
                  </div>
                )}
                {scope === 'selected_piece_size' && (
                  <div className="flex justify-between">
                    <span className="font-medium text-slate-500">Target Piece Size:</span>
                    <span className="font-bold text-slate-900">
                      {db.pieceSizes.find((p) => p.id === targetPieceSizeId)?.displayName || targetPieceSizeId}
                    </span>
                  </div>
                )}
                <div className="flex justify-between pt-1 border-t border-slate-100">
                  <span className="font-medium text-slate-500">Records to Purge:</span>
                  <span className="font-mono font-bold text-red-600">
                    {db.productionRecords.filter((r) => {
                      if (r.month !== currentMonthStr) return false;
                      if (scope === 'selected_worker') return r.workerId === targetWorkerId;
                      if (scope === 'selected_piece_size') return r.pieceSizeId === targetPieceSizeId;
                      return true;
                    }).length} records
                  </span>
                </div>
              </div>

              <p className="text-slate-600">
                To permanently wipe these entries from Supabase, type <strong className="text-red-700 font-bold">RESET</strong> in capital letters below:
              </p>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-600 uppercase mb-1">Type "RESET"</label>
              <input
                type="text"
                autoFocus
                value={confirmText}
                onChange={(e) => setConfirmText(e.target.value)}
                placeholder="RESET"
                className="w-full py-2.5 px-4 text-center tracking-widest font-mono font-bold text-lg rounded-lg bg-slate-50 border border-red-300 text-slate-900 focus:ring-2 focus:ring-red-500 focus:outline-none uppercase"
              />
            </div>

            <div className="flex items-center space-x-2 pt-1">
              <button
                type="button"
                onClick={handleResetWizard}
                className="w-1/2 py-2 rounded-lg bg-white hover:bg-slate-50 text-slate-700 text-xs font-bold border border-slate-300 shadow-xs cursor-pointer"
              >
                Abort
              </button>
              <button
                type="submit"
                disabled={loading || confirmText.trim().toUpperCase() !== 'RESET'}
                className="w-1/2 py-2 rounded-lg bg-red-600 hover:bg-red-700 text-white text-xs font-bold shadow-xs uppercase tracking-wider cursor-pointer disabled:opacity-50"
              >
                {loading ? 'Executing...' : 'EXECUTE ZERO'}
              </button>
            </div>
          </form>
        )}

        {/* STEP 4: Success Execution */}
        {step === 4 && (
          <div className="text-center py-5 space-y-3">
            <div className="inline-flex p-3 rounded-full bg-green-50 text-green-600 border border-green-200">
              <CheckCircle2 className="w-8 h-8" />
            </div>
            <h3 className="text-sm font-bold text-slate-900 uppercase">Zero Reset Completed</h3>
            <p className="text-xs text-slate-500 max-w-sm mx-auto leading-relaxed">
              The requested production entries have been wiped cleanly. An immutable audit entry has been logged to the
              system ledger.
            </p>

            <button
              type="button"
              onClick={handleResetWizard}
              className="py-2 px-5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs uppercase tracking-wider shadow-xs cursor-pointer"
            >
              Return to Zero System Menu
            </button>
          </div>
        )}
      </div>

      {/* Historical Audit of Zero Operations */}
      <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm space-y-2.5">
        <h3 className="text-xs font-bold text-slate-600 uppercase tracking-wider flex items-center space-x-1.5">
          <ShieldAlert className="w-3.5 h-3.5 text-amber-500" />
          <span>Zero Execution Audit Ledger</span>
        </h3>

        {db.zeroAudits.length === 0 ? (
          <div className="p-3 text-center text-slate-400 text-xs">No Zero operations recorded. System clean.</div>
        ) : (
          <div className="divide-y divide-slate-200 text-xs font-mono">
            {db.zeroAudits.map((za) => (
              <div key={za.id} className="py-2 flex items-center justify-between">
                <div>
                  <span className="font-bold text-slate-900">Scope: {za.scope}</span>
                  <span className="text-slate-500 ml-2">Month: {za.month}</span>
                  <div className="text-[10px] text-slate-400">{new Date(za.timestamp).toLocaleString()}</div>
                </div>
                <div className="text-right">
                  <span className="font-bold text-red-600">{za.recordsCountReset} records reset</span>
                  <div className="text-[10px] text-green-600 font-bold">OTP Verified</div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
